
export type Option = {
  id: string; // Will be auto-generated by MongoDB if not provided, or we can pre-generate
  text: string;
  imageUrl?: string;
  isCorrect: boolean;
  aiTags?: string[];
};

export type Question = {
  id: string; // Will be auto-generated by MongoDB if not provided, or we can pre-generate
  text: string;
  imageUrl?: string;
  aiTags?: string[];
  options: Option[];
  explanation?: string;
};

export type Quiz = {
  // id field will be automatically added by MongoDB as _id
  _id?: string; // MongoDB's default ID field, optional on creation
  title: string;
  testType: 'Previous Year' | 'Mock' | 'Practice Test';
  classType?: '11th' | '12th';
  subject?: 'Physics' | 'Chemistry' | 'Biology';
  chapter?: string;
  tags?: string[];
  timerMinutes?: number; // Added timer field
  questions: Question[];
  createdAt?: Date; // Optional: timestamp for when the quiz was created
  updatedAt?: Date; // Optional: timestamp for when the quiz was last updated
};

// For form state, we don't need MongoDB's _id or generated question/option IDs initially
export type QuizFormData = Omit<Quiz, '_id' | 'questions' | 'createdAt' | 'updatedAt'> & {
  questions: Array<Omit<Question, 'id' | 'options'> & {
    options: Array<Omit<Option, 'id'>>;
  }>;
};
